#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

[ -n "$CI" ] && exit 0

PATH="/usr/local/bin:$PATH"

# 一些lint操作包括 eslint、stylelint 等等，详情见lint-staged.config.js
pnpm exec lint-staged
